import fs from 'node:fs';
const path = 'frontend/src/App.tsx';
let s = fs.readFileSync(path, 'utf8');
const replace = (a,b) => { if (!s.includes(a)) throw new Error('Missing navigation anchor: '+a); s=s.replace(a,b); };
replace("  { key: 'projectAnalysis', path: '/analytics/project-portfolio', Icon: ProjectAnalysis },\n", '');
replace("  { key: 'documents', path: '/merl-reporting', search: '?module=evidence', Icon: FolderOpen },\n", '');
replace("const visibleNav = NAV_ITEMS.filter(n => allowed.includes(n.key));", "const visibleNav = NAV_ITEMS.filter(n => allowed.includes(n.key));");
replace("    ?? (location.pathname.startsWith('/analytics') ? NAV_ITEMS.find(n => n.key === 'results') : undefined)", "    ?? (location.pathname === '/analytics/project-portfolio' ? NAV_ITEMS.find(n => n.key === 'overview') : undefined)\n    ?? (location.pathname.startsWith('/analytics') ? NAV_ITEMS.find(n => n.key === 'results') : undefined)");
replace("  const activeItem = NAV_ITEMS.find(n => n.path === location.pathname", "  const activeItem = (location.pathname === '/merl-reporting' ? NAV_ITEMS.find(n => n.key === 'activities') : undefined)\n    ?? NAV_ITEMS.find(n => n.path === location.pathname");
fs.writeFileSync(path,s);
console.log('Removed duplicate portfolio and evidence sidebar entries; retained their routes and role permissions.');
