import { useCallback, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { CheckCircle2, RotateCcw, Eye, AlertTriangle, X, FileText } from '../components/ui/icons';
import { supabase } from '../supabaseClient';
import { confirmDialog, promptDialog } from '../lib/confirm';
import { dbErrorMessage } from '../lib/dbError';
import PageHeader from '../components/ui/PageHeader';
import StatTile from '../components/ui/StatTile';
import { fmtDate, fmtNum } from '../lib/locale';

const REVIEWER_ROLES=['ROLE_ADMIN','ROLE_DOCC_MEO'];
const SECTIONS=[
  ['indicator_progress','Indicator progress','v_indicator_progress',true],
  ['financial_progress','Financial progress','v_financial_progress',true],
  ['beneficiaries','Beneficiaries & GEDSI','v_beneficiaries',true],
  ['learning_updates','Achievements & learning','v_learning_updates',true],
  ['evidence','Evidence','v_evidence',true],
  ['risks_issues','Risks & issues','v_risks_issues',false],
];
const requiredKeys=['indicator_progress','financial_progress','learning_updates'];
const isOverdue=r=>r.period_end&&r.submission_status!=='approved'&&new Date(`${r.period_end}T23:59:59`)<new Date();
const rank={submitted:0,reviewed:1,returned:2,draft:3,approved:4};

export default function ReviewApproval({user}){
  const canReview=!!user&&REVIEWER_ROLES.includes(user.role);
  const [rows,setRows]=useState([]),[projects,setProjects]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[detail,setDetail]=useState(null);
  const [status,setStatus]=useState('queue'),[projectFilter,setProjectFilter]=useState(''),[query,setQuery]=useState('');
  const load=useCallback(async()=>{setLoading(true);const [rp,pj]=await Promise.all([supabase.from('v_reporting_periods').select('*'),supabase.from('v_projects').select('id,code,name')]);if(rp.error)toast.error(dbErrorMessage(rp.error));setRows(rp.data||[]);setProjects(pj.data||[]);setLoading(false);},[]);
  useEffect(()=>{load();},[load]);
  const byId=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,p])),[projects]);
  const kpi=useMemo(()=>{const k={submitted:0,reviewed:0,returned:0,approved:0,overdue:0};rows.forEach(r=>{if(k[r.submission_status]!=null)k[r.submission_status]++;if(isOverdue(r))k.overdue++;});return k;},[rows]);
  const visible=useMemo(()=>rows.filter(r=>{
    if(status==='queue'&&!['submitted','reviewed','returned'].includes(r.submission_status))return false;
    if(status==='approved'&&r.submission_status!=='approved')return false;
    if(status==='overdue'&&!isOverdue(r))return false;
    if(projectFilter&&r.project_id!==projectFilter)return false;
    const p=byId[r.project_id]; const q=query.trim().toLowerCase(); if(q&&!`${p?.code||''} ${p?.name||''} ${r.period_label||''}`.toLowerCase().includes(q))return false;
    return true;
  }).sort((a,b)=>(rank[a.submission_status]??9)-(rank[b.submission_status]??9)||String(a.period_end||'').localeCompare(String(b.period_end||''))),[rows,status,projectFilter,query,byId]);
  const act=async(rpc,params,msg)=>{setBusy(params.p_id);const {error}=await supabase.rpc(rpc,params);setBusy(null);if(error){toast.error(dbErrorMessage(error));return;}toast.success(msg);setDetail(null);load();};
  const review=r=>act('review_reporting_period',{p_id:r.id,p_decision:'review',p_comments:null},'Marked under review.');
  const returnForCorrection=async r=>{const c=await promptDialog({title:'Return for correction',label:'What needs correction?',required:true,multiline:true,message:'The Project Manager will see this feedback.'});if(c?.trim())act('review_reporting_period',{p_id:r.id,p_decision:'return',p_comments:c.trim()},'Report returned for correction.');};
  const approve=async r=>{if(!(await confirmDialog({title:'Approve reporting period?',message:'Approved information becomes the official reporting record and is locked until formally reopened.',confirmLabel:'Approve'})))return;act('review_reporting_period',{p_id:r.id,p_decision:'approve',p_comments:r.review_comments??null},'Reporting period approved.');};
  const reopen=async r=>{const reason=await promptDialog({title:'Reopen approved period',label:'Reason for reopening',required:true,multiline:true,message:'The reason is retained in the review history.'});if(reason?.trim())act('reopen_reporting_period',{p_id:r.id,p_reason:reason.trim()},'Reporting period reopened.');};
  return <div className="page-pad rv" style={{maxWidth:1280,margin:'0 auto'}}><style>{`
    .rv-filter{display:grid;grid-template-columns:1fr 1fr 1.4fr;gap:.6rem;margin:.8rem 0 1rem;padding:.8rem;background:#fff;border:1px solid var(--border);border-radius:12px}.rv-table-wrap{overflow:auto;border:1px solid var(--border);border-radius:12px;background:#fff}.rv-table{width:100%;border-collapse:collapse;font-size:.8rem}.rv-table th,.rv-table td{padding:.65rem .7rem;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}.rv-table th{position:sticky;top:0;background:var(--green-50);font-size:.65rem;text-transform:uppercase;letter-spacing:.04em;color:var(--text-3)}.rv-badge{display:inline-flex;padding:.18rem .48rem;border-radius:999px;font-size:.66rem;font-weight:700;background:#eef2f7}.rv-badge.overdue{background:#fee2e2;color:#991b1b}.rv-actions{display:flex;gap:.35rem;flex-wrap:wrap}.rv-btn{display:inline-flex;align-items:center;gap:.3rem;border:1px solid var(--border);border-radius:7px;background:#fff;padding:.38rem .55rem;font:inherit;font-size:.72rem;font-weight:700;cursor:pointer}.rv-drawer{position:fixed;inset:0;z-index:90;background:rgba(15,23,42,.32);display:flex;justify-content:flex-end}.rv-panel{width:min(760px,96vw);height:100%;overflow:auto;background:#fff;padding:1rem 1.1rem;box-shadow:-12px 0 30px rgba(0,0,0,.16)}.rv-panel-head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start;border-bottom:1px solid var(--border);padding-bottom:.8rem;margin-bottom:.8rem}.rv-section{border:1px solid var(--border);border-radius:10px;padding:.75rem;margin-bottom:.6rem}.rv-section h3{margin:0 0 .45rem;font-size:.85rem}.rv-grid{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.rv-item{padding:.55rem;background:#f8fafc;border-radius:8px;font-size:.75rem}.rv-validation{padding:.7rem;border-radius:9px;margin:.6rem 0}.rv-validation.ok{background:#ecfdf5;color:#166534}.rv-validation.warn{background:#fffbeb;color:#92400e}.rv-comment{padding:.7rem;background:#fff7ed;border:1px solid #fed7aa;border-radius:9px;font-size:.78rem}.rv-empty{padding:2rem;text-align:center;color:var(--text-3)}@media(max-width:760px){.rv-filter{grid-template-columns:1fr}.rv-grid{grid-template-columns:1fr}}
  `}</style><PageHeader title="Review & Approval" subtitle="Portfolio-wide queue for validating, returning, approving and reopening MERL reporting periods."/>
  {!canReview&&<div className="rv-validation warn"><AlertTriangle size={15}/> This account is read-only in the review workspace. Only the DoCC M&E Officer and System Administrator can take review decisions.</div>}
  <div className="grid-kpi" style={{marginBottom:'1rem'}}><StatTile label="Awaiting review" value={kpi.submitted}/><StatTile label="Under review" value={kpi.reviewed}/><StatTile label="Returned" value={kpi.returned}/><StatTile label="Approved" value={kpi.approved}/><StatTile label="Overdue" value={kpi.overdue} status={kpi.overdue?'red':'green'}/></div>
  <div className="rv-filter"><label><span className="field-label">Queue</span><select className="field-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="queue">Action queue</option><option value="all">All periods</option><option value="approved">Approved</option><option value="overdue">Overdue</option></select></label><label><span className="field-label">Project</span><select className="field-input" value={projectFilter} onChange={e=>setProjectFilter(e.target.value)}><option value="">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><label><span className="field-label">Search</span><input className="field-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Project or reporting period"/></label></div>
  {loading?<div className="rv-empty">Loading review queue…</div>:<div className="rv-table-wrap"><table className="rv-table"><thead><tr><th>Project</th><th>Period</th><th>Due date</th><th>Status</th><th>Reviewer comments</th><th>Actions</th></tr></thead><tbody>{visible.length?visible.map(r=>{const p=byId[r.project_id];return <tr key={r.id}><td><b>{p?.code||'—'}</b><br/>{p?.name||'Unknown project'}</td><td>{r.period_label}<br/><small>{r.period_type||''}</small></td><td>{fmtDate(r.period_end)}{isOverdue(r)&&<><br/><span className="rv-badge overdue">Overdue</span></>}</td><td><span className="rv-badge">{r.submission_status}</span></td><td>{r.review_comments||'—'}</td><td><div className="rv-actions"><button className="rv-btn" onClick={()=>setDetail(r)}><Eye size={14}/>Review</button>{canReview&&r.submission_status==='submitted'&&<button className="rv-btn" disabled={busy===r.id} onClick={()=>review(r)}>Start review</button>}{canReview&&['submitted','reviewed'].includes(r.submission_status)&&<button className="rv-btn" disabled={busy===r.id} onClick={()=>returnForCorrection(r)}><RotateCcw size={13}/>Return</button>}{canReview&&['submitted','reviewed'].includes(r.submission_status)&&<button className="rv-btn" disabled={busy===r.id} onClick={()=>approve(r)}><CheckCircle2 size={13}/>Approve</button>}{canReview&&r.submission_status==='approved'&&<button className="rv-btn" disabled={busy===r.id} onClick={()=>reopen(r)}><RotateCcw size={13}/>Reopen</button>}</div></td></tr>}):<tr><td colSpan="6"><div className="rv-empty">No reporting periods match these filters.</div></td></tr>}</tbody></table></div>}
  {detail&&<ReviewDrawer row={detail} project={byId[detail.project_id]} onClose={()=>setDetail(null)} canReview={canReview} busy={busy} review={review} returnForCorrection={returnForCorrection} approve={approve} reopen={reopen}/>}</div>;
}

function ReviewDrawer({row,project,onClose,canReview,busy,review,returnForCorrection,approve,reopen}){
  const [current,setCurrent]=useState({}),[previous,setPrevious]=useState({}),[loading,setLoading]=useState(true),[prevPeriod,setPrevPeriod]=useState(null);
  useEffect(()=>{let alive=true;(async()=>{setLoading(true);const {data:periods}=await supabase.from('v_reporting_periods').select('*').eq('project_id',row.project_id).eq('submission_status','approved').lt('period_end',row.period_end||'9999-12-31').order('period_end',{ascending:false}).limit(1);const prev=periods?.[0]||null;const reads=await Promise.all(SECTIONS.map(async([key,,view,scoped])=>{let q=supabase.from(view).select('*').eq('project_id',row.project_id);if(scoped)q=q.eq('reporting_period',row.period_label);const {data}=await q;return [key,data||[]];}));let prevReads=[];if(prev)prevReads=await Promise.all(SECTIONS.filter(x=>x[3]).map(async([key,,view])=>{const {data}=await supabase.from(view).select('*').eq('project_id',row.project_id).eq('reporting_period',prev.period_label);return [key,data||[]];}));if(alive){setCurrent(Object.fromEntries(reads));setPrevious(Object.fromEntries(prevReads));setPrevPeriod(prev);setLoading(false);}})();return()=>{alive=false;};},[row]);
  const missing=requiredKeys.filter(k=>!(current[k]||[]).length); const evidence=(current.evidence||[]).length; const ready=!missing.length;
  return <div className="rv-drawer" role="dialog" aria-modal="true" aria-label="Review reporting period"><div className="rv-panel"><div className="rv-panel-head"><div><h2 style={{margin:0}}>{project?.code} — {project?.name}</h2><p style={{margin:'.25rem 0 0',color:'var(--text-3)'}}>{row.period_label} · {row.submission_status} · due {fmtDate(row.period_end)}</p></div><button className="rv-btn" onClick={onClose} aria-label="Close"><X size={16}/></button></div>
  {row.review_comments&&<div className="rv-comment"><b>Existing reviewer feedback</b><br/>{row.review_comments}</div>}
  {loading?<div className="rv-empty">Loading submitted records…</div>:<><div className={`rv-validation ${ready?'ok':'warn'}`}><b>{ready?'Core reporting sections are present.':'Submission has validation gaps.'}</b><br/>{missing.length?`Missing saved records: ${missing.join(', ')}.`:'Indicator progress, financial progress and achievements/learning are present.'} Evidence attachments: {evidence}.</div>
  <div className="rv-grid">{SECTIONS.map(([key,label])=><div className="rv-section" key={key}><h3>{label}</h3><div><b>{fmtNum((current[key]||[]).length)}</b> record(s) this period</div>{prevPeriod&&previous[key]!==undefined&&<small>Previous approved period ({prevPeriod.period_label}): {fmtNum(previous[key].length)} record(s)</small>}<SectionPreview keyName={key} rows={current[key]||[]}/></div>)}</div></>}
  <div className="rv-actions" style={{position:'sticky',bottom:0,background:'#fff',padding:'1rem 0 0',borderTop:'1px solid var(--border)',marginTop:'1rem'}}>{canReview&&row.submission_status==='submitted'&&<button className="btn btn-secondary" disabled={busy===row.id} onClick={()=>review(row)}>Mark under review</button>}{canReview&&['submitted','reviewed'].includes(row.submission_status)&&<button className="btn btn-secondary" disabled={busy===row.id} onClick={()=>returnForCorrection(row)}>Return for correction</button>}{canReview&&['submitted','reviewed'].includes(row.submission_status)&&<button className="btn btn-primary" disabled={busy===row.id||!ready} title={!ready?'Core reporting sections are missing.':''} onClick={()=>approve(row)}>Approve reporting period</button>}{canReview&&row.submission_status==='approved'&&<button className="btn btn-secondary" disabled={busy===row.id} onClick={()=>reopen(row)}>Reopen approved period</button>}</div></div></div>;
}
function SectionPreview({keyName,rows}){if(!rows.length)return <div style={{color:'var(--text-3)',fontSize:'.72rem',marginTop:'.35rem'}}>No records.</div>;const text=r=>{if(keyName==='indicator_progress')return `${r.indicator_code||'Indicator'} · ${r.achievement_pct!=null?Math.round(r.achievement_pct)+'%':'actual '+(r.cumulative_actual??'—')}`;if(keyName==='financial_progress')return `Cumulative expenditure ${Number(r.cumulative_expenditure||0).toLocaleString('en-US')}`;if(keyName==='beneficiaries')return `${r.location||'All locations'} · direct ${fmtNum(r.total_direct||0)}`;if(keyName==='evidence')return r.title||r.file_name||'Evidence record';if(keyName==='risks_issues')return `${r.code||''} ${r.description||''}`.trim();return r.key_achievements||r.major_results||r.lessons_learned||r.narrative||'Recorded';};return <div style={{marginTop:'.35rem'}}>{rows.slice(0,3).map((r,i)=><div className="rv-item" key={r.id||i}>{String(text(r)).slice(0,150)}</div>)}{rows.length>3&&<small>+ {rows.length-3} more</small>}</div>;}
