-- =============================================================================
-- MERL Dashboard – Migration 0014: SRF framework columns backfill
-- =============================================================================
-- The Strategic Results Framework workbook carries columns the portal did not
-- surface: Responsibility, Timeframe, Budget Source, Achievement Narrative,
-- Next Step, Duration, 2025 % Achieved and 2025 Status. This registers them as
-- custom columns on the activities register and backfills each activity's value
-- from the workbook, matched by sort_order (stable since the 0010 seed).
-- Idempotent: column defs use ON CONFLICT DO NOTHING; the value merge is a
-- deterministic overwrite of these keys only.
-- =============================================================================

BEGIN;

DO $$
DECLARE base INT;
BEGIN
    SELECT COALESCE(MAX(sort_order),0) INTO base FROM merl.srf_columns;
    INSERT INTO merl.srf_columns (key, label, type, options, sort_order) VALUES
        ('responsibility', 'Responsibility', 'text', '[]'::jsonb, base+1),
        ('timeframe', 'Timeframe', 'text', '[]'::jsonb, base+2),
        ('budget_source', 'Budget Source', 'text', '[]'::jsonb, base+3),
        ('achievement_narrative', 'Achievement Narrative', 'text', '[]'::jsonb, base+4),
        ('next_step', 'Next Step', 'text', '[]'::jsonb, base+5),
        ('duration', 'Duration', 'text', '[]'::jsonb, base+6),
        ('2025_achieved', '2025 % Achieved', 'text', '[]'::jsonb, base+7),
        ('2025_status', '2025 Status', 'text', '[]'::jsonb, base+8)
    ON CONFLICT (key) DO NOTHING;
END $$;

UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners Stakeholders', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/CSO''s', 'achievement_narrative', '4 islands visited (Erromangp, Futuna, Aniwa & Anietyum)', 'next_step', 'DoCC to develop community Hazard Maps', 'duration', '2 weeks', '2025_status', 'Completed for Sanma now Malampa') WHERE sort_order = 1;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners Stakeholders, DLA, CSOs', 'timeframe', '2025-2030', 'budget_source', 'Development Partner/Donor/CSO''s', '2025_status', 'GGGI & VCAPII) support this development') WHERE sort_order = 2;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Communities Stakeholders', 'timeframe', '2025-2030', 'budget_source', 'Development Partner/Donor/CSO''s', 'achievement_narrative', 'Visited Tafea Outer islands area councils and communities', 'next_step', 'Needed more community awareness on climate change', 'duration', '2 weeks', '2025_status', 'Completed for Sanma now Malampa') WHERE sort_order = 3;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', '2 NPP developed this year only one is presented and pass through NAB while M&E NPP will passed through ACU (DSPPAC)', 'next_step', 'Need to review the feedbacks and re-developed', 'duration', '1 day', '2025_status', '2 NPPs') WHERE sort_order = 4;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2025-2030', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'IEC Materials, Use of KoboToolBox', 'next_step', 'Need more capacity training on systematic tools and climate change information', 'duration', '1 day') WHERE sort_order = 5;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Senior Officer (Procurement & Contracts)', 'timeframe', '2025-2030', 'budget_source', 'DoCC Budget') WHERE sort_order = 6;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'Developed COP strategy 2021-2026', 'next_step', 'Need to consulat with other agencies', 'duration', '1 day', '2025_achieved', '1') WHERE sort_order = 7;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'DOCC partner with Youth & Sports, Tourism Dept & Education', 'next_step', 'Completed activities with Y&S and Tourism project (Santo & Tanna) now preparing Climate Quiz with Tafea Secondary Schools in August', '2025_achieved', '1') WHERE sort_order = 8;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/CSO''s', 'achievement_narrative', 'Secondary schools outreach, Events outreach, Community outreach on tafea outer islands', 'duration', '1-2 days to 2 weeks', '2025_achieved', '0.3') WHERE sort_order = 9;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/CSO''s', 'achievement_narrative', 'CDCCC Plans facilated through NDMO support', '2025_achieved', '0.3') WHERE sort_order = 10;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/CSO''s', 'next_step', 'restructuring includes muncipality and provincial CC Positions', '2025_achieved', '0.3') WHERE sort_order = 11;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', '2025_achieved', 'still await assessments completed') WHERE sort_order = 12;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', '2025_achieved', 'same as above') WHERE sort_order = 13;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'PACRES supporting Environment of climate soft proof assessment, regulations of water resources management to restored river watershed for Port Vila Tagabe river', 'next_step', 'next tree planting event is 21 June Tree international day', '2025_achieved', '0.8') WHERE sort_order = 14;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor') WHERE sort_order = 15;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/Private Sector', '2025_achieved', 'ongoing') WHERE sort_order = 16;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'In-country Mitigation NDC document / report Developed', 'next_step', 'MRV on Track', 'duration', '2 months', '2025_achieved', 'ongoing') WHERE sort_order = 17;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'REDD+/Development Partner/Donor', 'achievement_narrative', 'NFI team have completed 12 islands; Aneityum, Tanna, Erromango, Efate, Santo, Malekula, Maewo, Ambrym, Gaua, Torres, Epi, Pentecost and Ambae.', 'next_step', 'A re-visited Team to Santo, Malekula, Ambae and Epi.', '2025_achieved', '100% NFI inventory') WHERE sort_order = 18;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2012-2023', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'on tracked', '2025_achieved', '0.3') WHERE sort_order = 19;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'achieved FCPF project on regular updates and reports on progress', 'next_step', 'FCPF extended to Decemeber 2021', '2025_achieved', 'ongoing support and engagement through to 2023') WHERE sort_order = 20;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'on tracked', '2025_achieved', '0.8') WHERE sort_order = 21;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/Private Sector') WHERE sort_order = 22;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'still on discussion between partners') WHERE sort_order = 23;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/CSO''s', '2025_achieved', '0.15') WHERE sort_order = 24;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/CSO''s', '2025_achieved', '0.3') WHERE sort_order = 25;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', '3 staffs graduated ( 1 PGDRR & 2 CCR). Staffs tking shorts online courses/ tarinings', 'next_step', 'Few staffs have specific training/courses on specific programes', 'duration', '1-2 semesters', '2025_achieved', '0.3') WHERE sort_order = 26;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'DOCC staffs having office devotion and also MOCCA Wednesdays devotion shedules', 'next_step', 'inform by MOCCA') WHERE sort_order = 27;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'DOCC support Shefa strategy planning integeting CC into their activities. Also DOCC part of the TWG', 'next_step', 'awaiting on other provinces') WHERE sort_order = 28;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'SPC supporting the CCDRR review. Draft developed', 'next_step', '1st inception workshop about to roll out soon', 'duration', '1 day workshop', '2025_achieved', '1') WHERE sort_order = 29;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'Project Screening, IEC materials approved, Support NAB on Positions interview screening', 'next_step', 'New NAB Planning & Policy position', 'duration', '1 day', '2025_achieved', '1') WHERE sort_order = 30;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', '2025_achieved', '0.5') WHERE sort_order = 31;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Climate Change Adaptation) -Lead; Communication, Outreach & Partnership Officer; Scientific Officer (Monitoring & Evaluation) Donors/Development Partners Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'completed Adaptation (Agriculture, Fishers & Water Sectors) NDC document to UNFCCC', 'next_step', 'Adaptation in UNFCCC TWG- preparation to next COP meeting', 'duration', '1 week workshop', '2025_achieved', '1') WHERE sort_order = 32;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Mitigation)- Lead Donors/Development Partners Stakeholders', 'timeframe', 'on-going', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'Mitigation and adaptation NDC submissions to UNFCCC', '2025_achieved', '1') WHERE sort_order = 33;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', 'on-going', 'budget_source', 'Development Partner/Donor/DoCC Budget', '2025_achieved', '1') WHERE sort_order = 34;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', 'on-going', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'New Business plan Templated develoed (PSC)', 'next_step', 'Draft 2022 Staffs workplans with budget submitted', 'duration', '1 day workshop', '2025_achieved', '1') WHERE sort_order = 35;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Scientific Officer (Monitoring & Evaluation) Communication, Outreach & Partnership Officer; Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/DoCC Budget', 'achievement_narrative', 'M&E framwork development still underway.', 'next_step', 'CCDRR review & CCDRR implementation plan & Corprate Plan review', 'duration', '2-3 months', '2025_achieved', '1') WHERE sort_order = 36;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Finance Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'Working with Y&S, Education to allocated funds for Sports and Quiz compettions', 'next_step', 'Climate change Quiz in August', 'duration', '1 week', '2025_achieved', '0.3') WHERE sort_order = 37;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Finance Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'Mandate by Finace dept.', 'next_step', 'Finance dept to endorsment', '2025_achieved', '0.3') WHERE sort_order = 38;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Finance Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'TBC', 'next_step', 'TBC', '2025_achieved', '0.7') WHERE sort_order = 39;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Finance Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/Private Sector', 'achievement_narrative', 'Planned to work with worldbank and Cooperative', 'next_step', 'TBC', '2025_achieved', '0.2') WHERE sort_order = 40;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Finance Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'attended training and having virtual zoom meetings to stregthen this areas', 'next_step', 'GGGI project to faciliated through NIE', '2025_achieved', '0.5') WHERE sort_order = 41;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/CSOs', 'achievement_narrative', '2 DOCC brochures deveoped and 4 banners endorzed and approved by NAB sec.', 'next_step', 'Tourism & CC brochures still on development stage + CC Quiz materials', '2025_achieved', '1') WHERE sort_order = 42;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor/CSOs', 'achievement_narrative', 'Supported by intern officers', 'next_step', 'recruitment of COMs officer', '2025_achieved', '1') WHERE sort_order = 43;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer', 'timeframe', 'on-going', 'budget_source', 'Development Partner/Donor/CSOs', 'achievement_narrative', 'Supported by intern officers', 'next_step', 'On track', 'duration', 'Q1-2', '2025_achieved', '0.8') WHERE sort_order = 44;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor/CSOs', 'achievement_narrative', 'litte efforts is put on awareness and Tourism project') WHERE sort_order = 45;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor/DOCC Budget', 'achievement_narrative', 'a day workshop on knowledge sharing after the (NPP) Small island awareness outreach & Vulnerability assessment on C impacts on Tafea Outer islands', 'next_step', 'compilation of reports and review', '2025_achieved', '0.7') WHERE sort_order = 46;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', 'On-going', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'National DRR and CC day', 'next_step', 'still on discussion (TBC)', '2025_achieved', '0.8') WHERE sort_order = 47;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'KOBO Tool Training, MRV Training', '2025_achieved', '0.8') WHERE sort_order = 48;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021 - 2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'National Geospaial data policy, DOCC GIS SOP developed', 'next_step', 'DOCC SOP developed for data sharing', '2025_achieved', '0.8') WHERE sort_order = 49;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'Tafea outer islands Lesson learnt workshop', 'next_step', 'compilation of reports and review', '2025_achieved', '0.7') WHERE sort_order = 50;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2012-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'working with NDMO & VMGD to resetup VanGeo Portal', 'next_step', 'Virtual meeting with SPC', '2025_achieved', '0.2') WHERE sort_order = 51;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'with the new directive from PSC no MOU is between government to government except for NGOs & CSOs', 'next_step', 'regional and internation partners continues to support and provide data and assistance supports were needed through request', '2025_achieved', '0.6') WHERE sort_order = 52;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', '2025_achieved', '0.7') WHERE sort_order = 53;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', '1 officer graduated in Post-Grade CC&DRR, 2 officers graduated on certificate 4 CCDRR resileince programe', 'next_step', 'Two officers to undertake USP course this 2nd semester- PACRES Funded', '2025_achieved', '0.6') WHERE sort_order = 54;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2022', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'Training of MRV tool ongoing', 'next_step', 'on tracked', '2025_achieved', '0.6') WHERE sort_order = 55;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'community and schools awareness programmes', 'next_step', 'educational CC Quiz', '2025_achieved', '0.6') WHERE sort_order = 56;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Relevant Scientific Officer Communication, Outreach & Partnership Officer Finance and Administration Officer Stakeholders', 'timeframe', '2021-2023', 'budget_source', 'Development Partner/Donor', 'achievement_narrative', 'DOCC supporting VCAPII, VCCRP & VANKIRAP Project on related researches, planning and delivery activities', 'next_step', 'DOCC Projects on design development stage', '2025_achieved', '0.5') WHERE sort_order = 57;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Director supported by Finance and Administration Officer', 'timeframe', '1st Qtr. of every year', 'budget_source', 'Internal', 'achievement_narrative', 'Completed', 'next_step', 'Submitted to PSC', '2025_achieved', '1') WHERE sort_order = 59;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '4th Qtr. of every year', 'budget_source', 'Internal', 'achievement_narrative', 'Completed', 'next_step', 'Submitted to Finance', '2025_achieved', '1') WHERE sort_order = 60;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'All Staff', 'timeframe', '2nd Qtr. of every year', 'budget_source', 'Internal', 'achievement_narrative', 'received all staffs monthly reports', 'next_step', 'M&E compiling reports', '2025_achieved', '1') WHERE sort_order = 61;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Communication, Outreach & Partnership Officer Scientific Officer (Monitoring & Evaluation)', 'timeframe', '1st Qtr. of every year', 'budget_source', 'Internal', 'achievement_narrative', 'Completed', 'next_step', 'M&E submitted to MOCCA', '2025_achieved', '1') WHERE sort_order = 62;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Director supported by Finance, M&E officer and Administration Officer', 'timeframe', 'on-going', 'budget_source', 'Internal', 'achievement_narrative', 'on tracked', 'next_step', 'SMR/ Q2 report developed, Restructuring in progress', '2025_achieved', '1') WHERE sort_order = 63;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Director supported by Finance and Administration Officer', 'timeframe', '4th Qtr. of every year', 'budget_source', 'Internal', 'achievement_narrative', 'Procurement and Finance SOP Developed', 'next_step', 'restructuing', 'duration', '6 months', '2025_achieved', '1') WHERE sort_order = 64;
UPDATE merl.srf_activities SET custom = COALESCE(custom,'{}'::jsonb) || jsonb_build_object('responsibility', 'Senior Officer (Procurement & Contracts) Finance and Administration Officer Support from all Staff', 'timeframe', '2021', 'budget_source', 'Development Partner/Donor/DOCC Budget', 'achievement_narrative', 'ongoing', 'next_step', 'operational', '2025_achieved', '1') WHERE sort_order = 65;

COMMIT;